# Generated by Django 4.2.1 on 2023-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('in_val', models.IntegerField()),
                ('out_val', models.IntegerField()),
                ('in_unit', models.TextField(default='cal')),
                ('out_unit', models.TextField(default='cal')),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('sleep_dur', models.FloatField()),
                ('start', models.TimeField(auto_now=True)),
                ('end', models.TimeField(auto_now=True)),
                ('unit', models.TextField(default='H')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('Steps_val', models.IntegerField()),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Walking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('Walking_val', models.FloatField()),
                ('time', models.DateField(auto_now=True)),
                ('unit', models.TextField(default='km')),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('weight_val', models.IntegerField()),
                ('time', models.DateField(auto_now=True)),
                ('unit', models.TextField(default='lb')),
            ],
        ),
    ]
