# Generated by Django 4.2.1 on 2023-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_weights_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weights',
            name='time',
            field=models.DateField(),
        ),
    ]
