# Generated by Django 4.2.1 on 2023-05-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_weights_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sleeping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
