# Generated by Django 4.2.1 on 2023-05-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_calorie_id_alter_sleeping_id_alter_steps_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Password', models.TextField()),
                ('Email', models.TextField(default='')),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
