# Generated by Django 4.2.1 on 2023-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='walking',
            name='time_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='walking',
            name='time',
            field=models.TextField(),
        ),
    ]
