# Generated by Django 4.2.1 on 2023-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_walking_time_created_alter_walking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='walking',
            name='Steps',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
    ]
