# Generated by Django 4.2.1 on 2023-05-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_walking_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
